// src/webview/common/components/PersonInfo.tsx
/**
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */
import type * as React from 'react';
import { getRelativeTimeString } from '../utils/time-utils';

export interface PersonInfoProps {
    person?: { name: string; email: string; timestamp: string };
    label: string;
}

export interface PersonDisplayStrings {
    nameToDisplay: string;
    emailToDisplay: string;
    fullTime: string;
    relTime: string;
    hasEmail: boolean;
}

export function getPersonDisplayStrings(person: {
    name: string;
    email: string;
    timestamp: string;
}): PersonDisplayStrings {
    const hasName = !!person.name && person.name !== '•';
    const hasEmail = !!person.email;

    const nameToDisplay = hasName ? person.name : hasEmail ? person.email : '(no name set)';
    const emailToDisplay = hasEmail ? person.email : '(no email set)';

    const fullTime = new Date(person.timestamp).toLocaleString();
    let relTime = person.timestamp;
    try {
        relTime = getRelativeTimeString(person.timestamp);
    } catch {
        // fallback to just rendering the timestamp string
    }

    return { nameToDisplay, emailToDisplay, fullTime, relTime, hasEmail };
}

export const PersonInfo: React.FC<PersonInfoProps> = ({ person, label }) => {
    if (!person) {
        return null;
    }

    const { nameToDisplay, emailToDisplay, fullTime, relTime, hasEmail } = getPersonDisplayStrings(person);

    return (
        <div style={{ display: 'flex', alignItems: 'center', fontSize: '13px' }} className="person-info">
            <span style={{ color: 'var(--vscode-descriptionForeground)', marginRight: '6px', flexShrink: 0 }}>
                {label}:
            </span>
            <strong style={{ color: 'var(--vscode-foreground)', marginRight: '6px', flexShrink: 0 }}>
                {nameToDisplay}
            </strong>
            <span
                style={{
                    color: hasEmail ? 'var(--vscode-descriptionForeground)' : 'var(--vscode-errorForeground)',
                    opacity: 0.7,
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                    flexShrink: 1,
                    minWidth: 0,
                }}
                title={`<${emailToDisplay}>`}
            >
                &lt;{emailToDisplay}&gt;
            </span>
            <span
                aria-hidden="true"
                style={{ color: 'var(--vscode-descriptionForeground)', margin: '0 6px', flexShrink: 0 }}
            >
                •
            </span>
            <time
                dateTime={person.timestamp}
                style={{ color: 'var(--vscode-foreground)', whiteSpace: 'nowrap', flexShrink: 0 }}
                title={fullTime}
            >
                {relTime}
            </time>
        </div>
    );
};

// src/core/webview/common/components/PersonInfo.svelte
<!--
  Copyright 2026 Google LLC
  SPDX-License-Identifier: Apache-2.0
-->
<script lang="ts">
import { getPersonDisplayStrings, type PersonInfoProps } from '../utils/person-utils';

let { person, label }: PersonInfoProps = $props();

let displayStrings = $derived(person ? getPersonDisplayStrings(person) : null);
</script>

{#if person && displayStrings}
    <div class="person-info">
        <span class="label">{label}:</span>
        <strong class="name">{displayStrings.nameToDisplay}</strong>
        <span
            class="email"
            class:no-email={!displayStrings.hasEmail}
            title="<{displayStrings.emailToDisplay}>"
        >
            &lt;{displayStrings.emailToDisplay}&gt;
        </span>
        <span aria-hidden="true" class="dot-separator">•</span>
        <time
            dateTime={person.timestamp}
            class="time"
            title={displayStrings.fullTime}
        >
            {displayStrings.relTime}
        </time>
    </div>
{/if}

<style>
    .person-info {
        display: flex;
        align-items: center;
        font-size: 13px;
    }

    .label {
        color: var(--vscode-descriptionForeground);
        margin-right: 6px;
        flex-shrink: 0;
    }

    .name {
        color: var(--vscode-foreground);
        margin-right: 6px;
        flex-shrink: 0;
    }

    .email {
        color: var(--vscode-descriptionForeground);
        opacity: 0.7;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        flex-shrink: 1;
        min-width: 0;
    }

    .email.no-email {
        color: var(--vscode-errorForeground);
    }

    .dot-separator {
        color: var(--vscode-descriptionForeground);
        margin: 0 6px;
        flex-shrink: 0;
    }

    .time {
        color: var(--vscode-foreground);
        white-space: nowrap;
        flex-shrink: 0;
    }
</style>
