// src/core/webview/log/components/DraggableBookmark.svelte
<!--
  Copyright 2026 Google LLC
  SPDX-License-Identifier: Apache-2.0
-->
<script lang="ts">
import type { JjBookmark } from '../../../jj-types';
import { BookmarkPill } from '../../common/components';
import type { DragManager } from '../drag-manager.svelte';

interface Props {
    bookmark: JjBookmark;
    dragManager: DragManager;
}

let { bookmark, dragManager }: Props = $props();

const isDragging = $derived(
    dragManager.activeDragItem?.type === 'bookmark' &&
        dragManager.activeDragItem.name === bookmark.name &&
        dragManager.activeDragItem.remote === bookmark.remote,
);
</script>

{#if bookmark.remote}
    <BookmarkPill {bookmark} />
{:else}
    <span
        class="draggable-bookmark"
        class:is-dragging={isDragging}
        use:dragManager.draggable={() => ({
            type: 'bookmark',
            name: bookmark.name,
            remote: bookmark.remote,
        })}
    >
        <BookmarkPill {bookmark} />
    </span>
{/if}

<style>
    .draggable-bookmark {
        cursor: grab;
        display: inline-flex;
        align-items: center;
        min-width: 22px;
        flex-shrink: 1;
    }

    .draggable-bookmark.is-dragging {
        cursor: grabbing;
        opacity: 0.3;
        filter: grayscale(100%);
    }
</style>

// src/webview/log/components/DraggableBookmark.tsx
/**
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */
import { useDraggable } from '@dnd-kit/core';
import type * as React from 'react';
import type { JjBookmark } from '../../../jj-types';
import { BookmarkPill } from '../../common/components/Bookmark';

export const DraggableBookmark: React.FC<{ bookmark: JjBookmark }> = ({ bookmark }) => {
    const { attributes, listeners, setNodeRef, isDragging } = useDraggable({
        id: `bookmark-${bookmark.name}-${bookmark.remote || 'local'}`,
        data: { type: 'bookmark', name: bookmark.name, remote: bookmark.remote },
        disabled: !!bookmark.remote,
    });

    if (bookmark.remote) {
        return <BookmarkPill bookmark={bookmark} />;
    }

    const style: React.CSSProperties = {
        cursor: isDragging ? 'grabbing' : 'grab',
        opacity: isDragging ? 0.3 : 1, // Show pending state
        filter: isDragging ? 'grayscale(100%)' : 'none',
        display: 'inline-flex',
        alignItems: 'center',
        minWidth: '22px',
        flexShrink: 1,
    };

    return (
        <span ref={setNodeRef} style={style} {...listeners} {...attributes}>
            <BookmarkPill bookmark={bookmark} />
        </span>
    );
};
